version: '3.8'
services:
  docs:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
  php-apache-environment:
    container_name: php-apache
    image: php:8.0-apache
    volumes:
      - ./php/src:/app
    ports:
      - 80:80